package com.project.saas.enums;

public enum Role {
    ADMIN,
    MANAGEMENT_STAFF,
    SALES_POINT,
    STATE_MANAGEMENT_STAFF,
    DISTRICT_MANAGEMENT_STAFF,
    CITY_MANAGEMENT_STAFF,
    ELECTRICIAN,
    BILLER,
    CUSTOMER,
    CMR,
    M1_MANAGER,
    M2_MANAGER,
    PERSONNEL,
    OPERATIONAL_HEAD,
    TENANT_ADMIN
}
