CREATE TABLE areas
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    code           VARCHAR(255)                            NOT NULL,
    electrician_id BIGINT,
    city_id        BIGINT                                  NOT NULL,
    biller_id      BIGINT,
    CONSTRAINT pk_areas PRIMARY KEY (id)
);




CREATE TABLE assign_work
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assigned_electrician_id BIGINT                                  NOT NULL,
    customers_id            BIGINT                                  NOT NULL,
    work_type               VARCHAR(255)                            NOT NULL,
    work_description        VARCHAR(255)                            NOT NULL,
    complaint_status        VARCHAR(255)                            NOT NULL,
    assigned_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_assign_work PRIMARY KEY (id)
);




CREATE TABLE cities
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                VARCHAR(255)                            NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    manager_user_id     BIGINT,
    district_service_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);


CREATE TABLE crm
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    cities_id BIGINT,
    CONSTRAINT pk_crm PRIMARY KEY (id)
);



CREATE TABLE customers
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    door_no VARCHAR(255)                            NOT NULL,
    area_id BIGINT                                  NOT NULL,
    crm_id  BIGINT,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);


CREATE TABLE customer_tenant
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    tenant_id   BIGINT                                  NOT NULL,
    area_id     BIGINT                                  NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_customer_tenant PRIMARY KEY (id)
);



CREATE TABLE districts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    manager_user_id BIGINT,
    state_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_districts PRIMARY KEY (id)
);


CREATE TABLE invitation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invitation_token VARCHAR(255)                            NOT NULL,
    issued_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    issued_to        VARCHAR(255)                            NOT NULL,
    role             VARCHAR(255),
    issuer_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_invitation PRIMARY KEY (id)
);


CREATE TABLE operating_tenant
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    sales_point      BIGINT,
    operating_tenant BIGINT,
    CONSTRAINT pk_operating_tenant PRIMARY KEY (id)
);



CREATE TABLE refresh_token
(
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (token)
);



CREATE TABLE states
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    code            VARCHAR(255)                            NOT NULL,
    manager_user_id BIGINT,
    CONSTRAINT pk_states PRIMARY KEY (id)
);





CREATE TABLE tenants
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    schema_name         VARCHAR(255)                            NOT NULL,
    tenant_status       VARCHAR(255)                            NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    subscription_amount DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);


CREATE TABLE tenant_available_states
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id        BIGINT                                   NOT NULL,
    available_states VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_tenantavailablestates PRIMARY KEY (id)
);

CREATE TABLE tenant_subscription_bills
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id   BIGINT                                  NOT NULL,
    bill_status VARCHAR(255)                            NOT NULL,
    amount_paid DOUBLE PRECISION                        NOT NULL,
    paid_date   date,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    CONSTRAINT pk_tenant_subscription_bills PRIMARY KEY (id)
);




CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    tenant_id  BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE assign_work
    ADD CONSTRAINT FK_ASSIGN_WORK_ON_ASSIGNED_ELECTRICIAN FOREIGN KEY (assigned_electrician_id) REFERENCES users (id);

ALTER TABLE assign_work
    ADD CONSTRAINT FK_ASSIGN_WORK_ON_CUSTOMERS FOREIGN KEY (customers_id) REFERENCES customers (id);

ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_DISTRICT_SERVICE FOREIGN KEY (district_service_id) REFERENCES districts (id);

ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_MANAGER_USER FOREIGN KEY (manager_user_id) REFERENCES users (id);



ALTER TABLE operating_tenant
    ADD CONSTRAINT uc_operating_tenant_operating_tenant UNIQUE (operating_tenant);

ALTER TABLE operating_tenant
    ADD CONSTRAINT uc_operating_tenant_sales_point UNIQUE (sales_point);

ALTER TABLE operating_tenant
    ADD CONSTRAINT uc_operating_tenant_user UNIQUE (user_id);

ALTER TABLE operating_tenant
    ADD CONSTRAINT FK_OPERATING_TENANT_ON_OPERATING_TENANT FOREIGN KEY (operating_tenant) REFERENCES tenants (id);

ALTER TABLE operating_tenant
    ADD CONSTRAINT FK_OPERATING_TENANT_ON_SALES_POINT FOREIGN KEY (sales_point) REFERENCES users (id);

ALTER TABLE operating_tenant
    ADD CONSTRAINT FK_OPERATING_TENANT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE states
    ADD CONSTRAINT FK_STATES_ON_MANAGER_USER FOREIGN KEY (manager_user_id) REFERENCES users (id);
ALTER TABLE tenants
    ADD CONSTRAINT uc_tenants_name UNIQUE (name);

ALTER TABLE tenants
    ADD CONSTRAINT uc_tenants_schema_name UNIQUE (schema_name);

ALTER TABLE tenant_available_states
    ADD CONSTRAINT FK_TENANTAVAILABLESTATES_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenants (id);


ALTER TABLE tenant_subscription_bills
    ADD CONSTRAINT FK_TENANT_SUBSCRIPTION_BILLS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenants (id);


ALTER TABLE areas
    ADD CONSTRAINT uc_areas_biller UNIQUE (biller_id);

ALTER TABLE areas
    ADD CONSTRAINT uc_areas_electrician UNIQUE (electrician_id);

ALTER TABLE areas
    ADD CONSTRAINT uc_areas_name UNIQUE (name);

ALTER TABLE areas
    ADD CONSTRAINT FK_AREAS_ON_BILLER FOREIGN KEY (biller_id) REFERENCES users (id);

ALTER TABLE areas
    ADD CONSTRAINT FK_AREAS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE areas
    ADD CONSTRAINT FK_AREAS_ON_ELECTRICIAN FOREIGN KEY (electrician_id) REFERENCES users (id);


ALTER TABLE crm
    ADD CONSTRAINT uc_crm_user UNIQUE (user_id);

ALTER TABLE crm
    ADD CONSTRAINT FK_CRM_ON_CITIES FOREIGN KEY (cities_id) REFERENCES cities (id);

ALTER TABLE crm
    ADD CONSTRAINT FK_CRM_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);



ALTER TABLE customer_tenant
    ADD CONSTRAINT FK_CUSTOMER_TENANT_ON_AREA FOREIGN KEY (area_id) REFERENCES areas (id);

ALTER TABLE customer_tenant
    ADD CONSTRAINT FK_CUSTOMER_TENANT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE customer_tenant
    ADD CONSTRAINT FK_CUSTOMER_TENANT_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE districts
    ADD CONSTRAINT FK_DISTRICTS_ON_MANAGER_USER FOREIGN KEY (manager_user_id) REFERENCES users (id);

ALTER TABLE districts
    ADD CONSTRAINT FK_DISTRICTS_ON_STATE FOREIGN KEY (state_id) REFERENCES states (id);

ALTER TABLE invitation
    ADD CONSTRAINT uc_invitation_invitationtoken UNIQUE (invitation_token);

ALTER TABLE invitation
    ADD CONSTRAINT FK_INVITATION_ON_ISSUER FOREIGN KEY (issuer_id) REFERENCES users (id);

ALTER TABLE customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_AREA FOREIGN KEY (area_id) REFERENCES areas (id);

ALTER TABLE customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_CRM FOREIGN KEY (crm_id) REFERENCES crm (id);

ALTER TABLE customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

