
CREATE TABLE master.users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE master.user_roles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    role    VARCHAR(255),
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);




CREATE TABLE master.tenant_subscription_bills
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id   BIGINT                                  NOT NULL,
    bill_status VARCHAR(255)                            NOT NULL,
    amount_paid DOUBLE PRECISION                        NOT NULL,
    paid_date   date                                    NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    CONSTRAINT pk_tenant_subscription_bills PRIMARY KEY (id)
);




CREATE TABLE master.tenant_available_states
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id        BIGINT                                   NOT NULL,
    available_states VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_tenantavailablestates PRIMARY KEY (id)
);



CREATE TABLE master.tenants
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    schema_name         VARCHAR(255)                            NOT NULL,
    tenant_schema       VARCHAR(255)                            NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    operational_head_id BIGINT                                  NOT NULL,
    point_of_contact_id BIGINT                                  NOT NULL,
    subscription_amount DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);




CREATE TABLE master.states
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    code            VARCHAR(255)                            NOT NULL,
    manager_user_id BIGINT,
    CONSTRAINT pk_states PRIMARY KEY (id)
);




CREATE TABLE master.refresh_token
(
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (token)
);




CREATE TABLE master.meters
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                VARCHAR(255)                            NOT NULL,
    rate_per_unit       DOUBLE PRECISION                        NOT NULL,
    photos_required     INTEGER                                 NOT NULL,
    interval_btw_photos INTEGER                                 NOT NULL,
    tenant_id           BIGINT,
    CONSTRAINT pk_meters PRIMARY KEY (id)
);





CREATE TABLE master.invitation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invitation_token VARCHAR(255)                            NOT NULL,
    issued_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    issued_to        VARCHAR(255)                            NOT NULL,
    role             VARCHAR(255),
    issuer_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_invitation PRIMARY KEY (id)
);




CREATE TABLE master.districts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    manager_user_id BIGINT,
    state_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_districts PRIMARY KEY (id)
);




CREATE TABLE master.customer_tenant
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    tenant_id   BIGINT                                  NOT NULL,
    meter_id    BIGINT                                  NOT NULL,
    area_id     BIGINT                                  NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_customer_tenant PRIMARY KEY (id)
);







CREATE TABLE master.customers
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    area_id BIGINT                                  NOT NULL,
    crm_id  BIGINT,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);






CREATE TABLE master.cities
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                VARCHAR(255)                            NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    manager_user_id     BIGINT,
    district_service_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);




CREATE TABLE master.areas
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    code           VARCHAR(255)                            NOT NULL,
    electrician_id BIGINT,
    city_id        BIGINT                                  NOT NULL,
    biller_id      BIGINT,
    CONSTRAINT pk_areas PRIMARY KEY (id)
);



ALTER TABLE master.areas
    ADD CONSTRAINT uc_areas_name UNIQUE (name);

ALTER TABLE master.areas
    ADD CONSTRAINT FK_AREAS_ON_BILLER FOREIGN KEY (biller_id) REFERENCES master.users (id);

ALTER TABLE master.areas
    ADD CONSTRAINT FK_AREAS_ON_CITY FOREIGN KEY (city_id) REFERENCES master.cities (id);

ALTER TABLE master.areas
    ADD CONSTRAINT FK_AREAS_ON_ELECTRICIAN FOREIGN KEY (electrician_id) REFERENCES master.users (id);





ALTER TABLE master.districts
    ADD CONSTRAINT FK_DISTRICTS_ON_MANAGER_USER FOREIGN KEY (manager_user_id) REFERENCES master.users (id);

ALTER TABLE master.districts
    ADD CONSTRAINT FK_DISTRICTS_ON_STATE FOREIGN KEY (state_id) REFERENCES master.states (id);

ALTER TABLE master.customer_tenant
    ADD CONSTRAINT FK_CUSTOMER_TENANT_ON_AREA FOREIGN KEY (area_id) REFERENCES master.areas (id);

ALTER TABLE master.customer_tenant
    ADD CONSTRAINT FK_CUSTOMER_TENANT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES master.customers (id);

ALTER TABLE master.customer_tenant
    ADD CONSTRAINT FK_CUSTOMER_TENANT_ON_METER FOREIGN KEY (meter_id) REFERENCES master.meters (id);

ALTER TABLE master.customer_tenant
    ADD CONSTRAINT FK_CUSTOMER_TENANT_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES master.tenants (id);
ALTER TABLE master.customers
    ADD CONSTRAINT uc_customers_user UNIQUE (user_id);

ALTER TABLE master.customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_AREA FOREIGN KEY (area_id) REFERENCES master.customers (id);

ALTER TABLE master.customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_CRM FOREIGN KEY (crm_id) REFERENCES master.users (id);

ALTER TABLE master.customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_USER FOREIGN KEY (user_id) REFERENCES master.users (id);


ALTER TABLE master.cities
    ADD CONSTRAINT FK_CITIES_ON_DISTRICT_SERVICE FOREIGN KEY (district_service_id) REFERENCES master.districts (id);

ALTER TABLE master.cities
    ADD CONSTRAINT FK_CITIES_ON_MANAGER_USER FOREIGN KEY (manager_user_id) REFERENCES master.users (id);


ALTER TABLE master.tenants
    ADD CONSTRAINT uc_tenants_name UNIQUE (name);

ALTER TABLE master.tenants
    ADD CONSTRAINT uc_tenants_operational_head UNIQUE (operational_head_id);

ALTER TABLE master.tenants
    ADD CONSTRAINT uc_tenants_point_of_contact UNIQUE (point_of_contact_id);

ALTER TABLE master.tenants
    ADD CONSTRAINT uc_tenants_schema_name UNIQUE (schema_name);

ALTER TABLE master.tenants
    ADD CONSTRAINT uc_tenants_tenant_schema UNIQUE (tenant_schema);

ALTER TABLE master.tenants
    ADD CONSTRAINT FK_TENANTS_ON_OPERATIONAL_HEAD FOREIGN KEY (operational_head_id) REFERENCES master.users (id);

ALTER TABLE master.tenants
    ADD CONSTRAINT FK_TENANTS_ON_POINT_OF_CONTACT FOREIGN KEY (point_of_contact_id) REFERENCES master.users (id);

ALTER TABLE master.states
    ADD CONSTRAINT FK_STATES_ON_MANAGER_USER FOREIGN KEY (manager_user_id) REFERENCES master.users (id);

ALTER TABLE master.refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES master.users (id);

ALTER TABLE master.meters
    ADD CONSTRAINT FK_METERS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES master.tenants (id);

ALTER TABLE master.invitation
    ADD CONSTRAINT uc_invitation_invitationtoken UNIQUE (invitation_token);

ALTER TABLE master.invitation
    ADD CONSTRAINT FK_INVITATION_ON_ISSUER FOREIGN KEY (issuer_id) REFERENCES master.users (id);



ALTER TABLE master.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE master.users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE master.user_roles
    ADD CONSTRAINT FK_USER_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES master.users (id);

ALTER TABLE master.tenant_subscription_bills
    ADD CONSTRAINT FK_TENANT_SUBSCRIPTION_BILLS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES master.tenants (id);

ALTER TABLE master.tenant_available_states
    ADD CONSTRAINT FK_TENANTAVAILABLESTATES_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES master.tenants (id);



